; =====================================================================
;  Konfigurasi PHP untuk Drupal — dipasang oleh docker-compose.yml ke
;  /usr/local/etc/php/conf.d/custom.ini
; =====================================================================
memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 600
max_input_time = 600
max_input_vars = 5000
date.timezone = Asia/Jakarta

; --- OPcache (Drupal sangat terbantu) ---
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 2

display_errors = Off
allow_url_fopen = On
